//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsIra2
{
    [Serializable]
    public class HapticInfoMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_ira2/HapticInfo";
        public override string RosMessageName => k_RosMessageName;

        public int button;
        public Geometry.PoseStampedMsg pose;

        public HapticInfoMsg()
        {
            this.button = 0;
            this.pose = new Geometry.PoseStampedMsg();
        }

        public HapticInfoMsg(int button, Geometry.PoseStampedMsg pose)
        {
            this.button = button;
            this.pose = pose;
        }

        public static HapticInfoMsg Deserialize(MessageDeserializer deserializer) => new HapticInfoMsg(deserializer);

        private HapticInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.button);
            this.pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.button);
            serializer.Write(this.pose);
        }

        public override string ToString()
        {
            return "HapticInfoMsg: " +
            "\nbutton: " + button.ToString() +
            "\npose: " + pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
